### ISSUE TITLE
The password of sample data for testing RSA-GiA

### ISSUE THREAD

**Issue by lisen0802** [Topp-Roots-Lab/rsa-gui#32]
Dear Parker, I am a young researcher from China, your software of RSA-GIA is tiptop, I'm very interested in it. I take the liberty of contacting you, can you provide the password of sample data for testing RSA-GiA provided Ni Jiang to verify that the software installation was successful? My email is lisen0802@gmail.com, looking forward to your reply. In addition, there is a small spelling error in the test code, "stat" should be "stats".

**Comment by tparkerd** [comment]
Hi Lisen, thank you for catching that typo, and I apologize for the massive delay in my reply. If you're still interested, I shared the test data with you via SharePoint to the provided email.

Unfortunately, we've had to retire that endpoint and have since replaced it with Microsoft SharePoint. Let me know if you have any issues accessing the data.

**Comment by lisen0802** [comment]
Hi Tim Parker, 


thank you for your reply. Now I install the software of RSA-GiA, but it still lacks verification. Therefore, I'm still interested in the test data.  I really hope you can share them.


Thanks again.


Sen Li
Farmland Irrigation Research Institute (FIRI) of Chinese Academy of Agricultural Sciences (CAAS)


| |
李森
|
|
***@***.***
|
---- Replied Message ----
| From | Tim ***@***.***> |
| Date | 10/14/2022 05:23 |
| To | ***@***.***> |
| Cc | Sen ***@***.***> ,
***@***.***> |
| Subject | Re: [Topp-Roots-Lab/rsa-gui] The password of sample data for testing RSA-GiA (Issue #32) |

Hi Lisen, thank you for catching that typo, and I apologize for the massive delay in my reply. If you're still interested, I shared the test data with you via SharePoint to the provided email.

Unfortunately, we've had to retire that endpoint and have since replaced it with Microsoft SharePoint. Let me know if you have any issues accessing the data.
